// One-time setup for a fresh clone: creates server/.env for local development
// and finishes the embedded-Postgres install step that npm blocks by default.
// Safe to re-run; it never overwrites an existing .env.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');

const ROOT = path.join(__dirname, '..');
const ENV_PATH = path.join(ROOT, 'server', '.env');

const LOCAL_DB_URL = 'postgresql://campus:campus@localhost:55432/campusconnect';

function writeEnv() {
  if (fs.existsSync(ENV_PATH)) {
    console.log('server/.env already exists — leaving it untouched.');
    return;
  }

  const contents = `# Local development config, generated by "npm run setup".
# Points at the local Postgres started by "npm run db".
DATABASE_URL=${LOCAL_DB_URL}
DATABASE_SSL=false

PORT=4000
CLIENT_ORIGIN=http://localhost:5173

# Unique to this machine. Production must set its own.
JWT_SECRET=${crypto.randomBytes(48).toString('hex')}

ALLOWED_EMAIL_DOMAINS=hitam.org

# Relaxed locally so development and testing aren't locked out.
RATE_LIMIT_SIGNUP_MAX=100
RATE_LIMIT_LOGIN_MAX=100
`;

  fs.writeFileSync(ENV_PATH, contents);
  console.log('Created server/.env with a freshly generated JWT_SECRET.');
}

// npm blocks this package's postinstall, which leaves the Postgres binaries
// without their symlinks. Running it here keeps `npm run db` working.
function hydratePostgres() {
  const pkgDirs = fs
    .readdirSync(path.join(ROOT, 'server', 'node_modules', '@embedded-postgres'), {
      withFileTypes: true,
    })
    .filter((d) => d.isDirectory())
    .map((d) => path.join(ROOT, 'server', 'node_modules', '@embedded-postgres', d.name));

  for (const dir of pkgDirs) {
    const script = path.join(dir, 'scripts', 'hydrate-symlinks.js');
    if (!fs.existsSync(script)) continue;
    execFileSync(process.execPath, [script], { cwd: dir, stdio: 'ignore' });
    console.log(`Prepared Postgres binaries in ${path.basename(dir)}.`);
  }
}

writeEnv();

try {
  hydratePostgres();
} catch (err) {
  console.warn(
    `Could not prepare the local Postgres binaries (${err.message}).\n` +
      'If "npm run db" fails, set DATABASE_URL in server/.env to a hosted Postgres instead.'
  );
}

console.log('\nSetup complete. Next:');
console.log('  npm run db     # terminal 1 — start local Postgres');
console.log('  npm run seed   # terminal 2 — create tables + demo data');
console.log('  npm run dev    # terminal 2 — start the app');
